app_args:
        output_dir: 'logs'
        name: null
        deterministic: True
        global_seed: 0

op_mode_args:
        evaluate_model_mode: False
        train_model_mode: False
        test_timeloop_accelergy_mode: False

model_args:
        arch: [mobilenet_cifar10, resnet18_cifar100]
        workers: 15
        batch_size: 64
        load_serialized: False
        gpus: 0
        cpu: False
        validation_split: 0.3
        effective_train_size: 0.5
        effective_valid_size: 0.5
        effective_test_size: 1
        batch_print_frequency: 100
        model_verbose: False
        model_save_frequency: 1
        use_profiler: False
        train_epochs: 1
        #resumed_checkpoint_path: /workspace/chkpts/cifar10/mobilenet_cifar10.pth
        pretrained: True

optimizer_args:
        optimizer_type: sgd
        learning_rate: 0.1
        momentum: 0.9
        weight_decay: 1.e-4

rl_args:
        rl_retrain_epochs: 0
        rl_reward_type: acc_size
        rl_pruning_high: 0.99
        rl_pruning_low: 0.01
        rl_quant_high: 8
        rl_quant_low: 8
        rl_top1_constraint: 2
        rl_top5_constraint: null
        rl_loss_constraint: null
        rl_energy_constraint: null
        rl_sparsity_constraint: null
        rl_size_constraint: 50
        rl_pruning_group_type: columns

