app_args:
        output_dir: 'logs'
        name: null
        deterministic: True
        global_seed: 0
        dnn_accuracy_lut_file: null

op_mode_args:
        evaluate_model_mode: False
        train_model_mode: False
        test_timeloop_accelergy_mode: False

model_args:
        arch: [resnet18_cifar100, vgg11_cifar10]
        workers: 15
        batch_size: 64
        load_serialized: False
        gpus: 0
        cpu: False
        validation_split: 0.3
        effective_train_size: 0.5
        effective_valid_size: 0.5
        effective_test_size: 1
        batch_print_frequency: 100
        model_verbose: False
        model_save_frequency: 1
        use_profiler: False
        train_epochs: 1
        #resumed_checkpoint_path: /workspace/chkpts/cifar10/mobilenet_cifar10.pth
        pretrained: True

optimizer_args:
        optimizer_type: sgd
        learning_rate: 0.1
        momentum: 0.9
        weight_decay: 1.e-4

compression_args:
        pruning_group_type: columns
        pruning_high: 0.99
        pruning_low: 0.01
        pruning_incr: 0.05
        quant_high: 8
        quant_low: 5
        quant_incr: 1
        top1_constraint: 2
        top5_constraint: null
        loss_constraint: null
        use_validation_set: False
        size_constraint: 50
        sparsity_constraint: null
 
rl_env_args:
        rl_retrain_epochs: 0
        rl_model_save_frequency: 1
        rl_reward_type: acc_size
        rl_energy_constraint: null
        rl_sparsity_constraint: null
        rl_size_constraint: 50

rl_agent_args:
        rl_agent_verbose: True
        # timesteps are identical for our experiment, but do
        #  not trigger a callback
        rl_agent_total_timesteps: 400
        # episodes trigger a termination callback
        rl_agent_train_episodes: null
        # this turns on post-training evaluation
        rl_agent_eval_episodes: null
        rl_agent_deterministic: False
        rl_agent_batch_size: 64
        rl_agent_save_frequency: 5
        # this turns on evaluation intervals within training
        rl_agent_eval_frequency: 2
        rl_agent_no_improv_evals: 10
        rl_agent_min_evals: 50
        rl_agent_policy_device: 'cpu'
        rl_agent_load_from_path: null

accel_args:
        accelerator_arch_type: eyeriss

