---
# Setting workloads according to: https://arxiv.org/abs/2210.14657
# and the MLPerf suite: https://github.com/mlcommons/inference
workloads:
  ImageClassifiers:
    - arch: vgg11
      dataset: cifar10
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    - arch: resnet18
      dataset: cifar10
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    - arch: efficientnet
      dataset: cifar10
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    - arch: vgg16
      dataset: cifar100
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    - arch: resnet50
      dataset: cifar100
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    - arch: mobilenetv2
      dataset: cifar100
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
  RestTasks:
    # image segmentation
    - arch: unet_3d
      dataset: voc_seg
      pretrained: true
      batch_size: 1
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    # language processing
    - arch: t5
      dataset: multi30k
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    # object detection
    - arch: tinyyolov2
      dataset: voc_det
      pretrained: true
      resumed_checkpoint_path: null
      batch_print_frequency: 100
    # recommendation
    # - arch: dlrm_v2
    #   dataset: criteo
    #   pretrained: true
    #   resumed_checkpoint_path: null
    #   batch_print_frequency: 100
